// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrzkpoysgsybrkuennkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpyemtwb3lzZ3N5YnJrdWVubmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjMxNzksImV4cCI6MjA1OTQ5OTE3OX0.IcM6TeQW_8Gh9lWBEogljfG_iaBGP7J7W19SPkXWADo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);